# backend = "xrender"
# blur-method = "gaussian"
# blur-size = 10
# blur-deviation = 5

backend = "glx"
# blur-method = "dual_kawase"
# blur-strength = 2

shadow = false
fading = false
vsync = true

# only blur Alacritty window
blur-background-exclude = [
  "!class_g = 'Alacritty'"
];
