#!/bin/sh

# remap
setxkbmap -layout us,th -option grp:win_space_toggle

# autostart
pkill sxhkd; sxhkd &
pkill polkit-gnome-au; /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# pkill picom; picom &
pkill polybar; polybar -c "$HOME/.config/polybar/config.ini" main &
pkill greenclip; greenclip clear; greenclip daemon &
xclip -selection clipboard /dev/null
feh --no-fehbg --bg-fill "$HOME/.config/wallpaper/wallpaper"
pkill dunst; # dunst is auto-start
rfkill block bluetooth

# bspwm config
bspc monitor -d                     1 2 3 4
bspc config border_width	    			1
bspc config window_gap		    			0
bspc config normal_border_color     "#1e222a"
bspc config focused_border_color    "#abb2bf"
bspc config presel_feedback_color   "#abb2bf"
bspc config swallow_first_click     false
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config swallow_first_click     false
bspc config focus_follows_pointer   false
bspc config pointer_follows_focus   false
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc rule -a "Nsxiv" state=floating
bspc rule -a "Kvantum Manager" state=floating
# bspc rule -a "Brave-browser" desktop='^2'
