[color]

black = #1e222a
white = #abb2bf
grey = #353b45
yellow = #e5c07b
orange = #d19a66
red = #e06c75
green = #98c379
blue = #61afef
teal = #56b6c2
purple = #c678dd

; black = #1d2021
; white = #d4be98
; yellow = #D8A657
; red = #EA6962
; green = #A9B665
; blue = #7DAEA3
; teal = #89b482
